export const CHAPITRE_LIST_REQUEST = 'CHAPITRE_LIST_REQUEST';
export const CHAPITRE_LIST_SUCCESS = 'CHAPITRE_LIST_SUCCESS';
export const CHAPITRE_LIST_FAIL = 'CHAPITRE_LIST_FAIL';

export const CHAPITRE_DETAILS_REQUEST = 'CHAPITRE_DETAILS_REQUEST';
export const CHAPITRE_DETAILS_SUCCESS = 'CHAPITRE_DETAILS_SUCCESS';
export const CHAPITRE_DETAILS_FAIL = 'CHAPITRE_DETAILS_FAIL';
