export const SET_INSCRIPTION_DATA = 'SET_INSCRIPTION_DATA'
export const RESET_INSCRIPTION_DATA = 'RESET_INSCRIPTION_DATA'
export const INSCRIPTION_SUBMIT_REQUEST = 'INSCRIPTION_SUBMIT_REQUEST';
export const INSCRIPTION_SUBMIT_SUCCESS = 'INSCRIPTION_SUBMIT_SUCCESS';
export const INSCRIPTION_SUBMIT_FAIL = 'INSCRIPTION_SUBMIT_FAIL';  
export const INSCRIPTION_LIST_MY_REQUEST = 'INSCRIPTION_LIST_MY_REQUEST';
export const INSCRIPTION_LIST_MY_SUCCESS = 'INSCRIPTION_LIST_MY_SUCCESS';
export const INSCRIPTION_LIST_MY_FAIL = 'INSCRIPTION_LIST_MY_FAIL';
export const INSCRIPTION_DETAILS_FAIL = 'INSCRIPTION_DETAILS_FAIL';
export const INSCRIPTION_DETAILS_SUCCESS = 'INSCRIPTION_DETAILS_SUCCESS';
export const INSCRIPTION_DETAILS_REQUEST = 'INSCRIPTION_DETAILS_REQUEST';
 export const INSCRIPTION_LIST_ADMIN_REQUEST = 'INSCRIPTION_LIST_ADMIN_REQUEST';
export const INSCRIPTION_LIST_ADMIN_SUCCESS = 'INSCRIPTION_LIST_ADMIN_SUCCESS';
export const INSCRIPTION_LIST_ADMIN_FAIL = 'INSCRIPTION_LIST_ADMIN_FAIL';

  
export const INSCRIPTION_DELETE_REQUEST = 'INSCRIPTION_DELETE_REQUEST'
export const INSCRIPTION_DELETE_SUCCESS = 'INSCRIPTION_DELETE_SUCCESS'
export const INSCRIPTION_DELETE_FAIL = 'INSCRIPTION_DELETE_FAIL'

export const INSCRIPTION_UPDATE_STATUS_REQUEST = 'INSCRIPTION_UPDATE_STATUS_REQUEST'
export const INSCRIPTION_UPDATE_STATUS_SUCCESS = 'INSCRIPTION_UPDATE_STATUS_SUCCESS'
export const INSCRIPTION_UPDATE_STATUS_FAIL = 'INSCRIPTION_UPDATE_STATUS_FAIL'
  
  