export const SEANCE_LIST_REQUEST = 'SEANCE_LIST_REQUEST';
export const SEANCE_LIST_SUCCESS = 'SEANCE_LIST_SUCCESS';
export const SEANCE_LIST_FAIL = 'SEANCE_LIST_FAIL';

export const SEANCE_DETAILS_REQUEST = 'SEANCE_DETAILS_REQUEST';
export const SEANCE_DETAILS_SUCCESS = 'SEANCE_DETAILS_SUCCESS';
export const SEANCE_DETAILS_FAIL = 'SEANCE_DETAILS_FAIL';

export const SEANCE_JOIN_REQUEST = 'SEANCE_JOIN_REQUEST';
export const SEANCE_JOIN_SUCCESS = 'SEANCE_JOIN_SUCCESS';
export const SEANCE_JOIN_FAIL = 'SEANCE_JOIN_FAIL';
